/*
Deployment script for PoCBalanceMonitor

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "PoCBalanceMonitor"
:setvar DefaultFilePrefix "PoCBalanceMonitor"
:setvar DefaultDataPath "C:\Users\Goose\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\Goose\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Starting rebuilding table [dbo].[AccountBalance]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_AccountBalance] (
    [Id]        INT              IDENTITY (1, 1) NOT NULL,
    [AccountId] UNIQUEIDENTIFIER NOT NULL,
    [Currency]  NCHAR (3)        NOT NULL,
    [Amount]    DECIMAL (18, 6)  NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_AccountBalance] PRIMARY KEY CLUSTERED ([AccountId] ASC, [Currency] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[AccountBalance])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AccountBalance] ON;
        INSERT INTO [dbo].[tmp_ms_xx_AccountBalance] ([AccountId], [Currency], [Id], [Amount])
        SELECT   [AccountId],
                 [Currency],
                 [Id],
                 [Amount]
        FROM     [dbo].[AccountBalance]
        ORDER BY [AccountId] ASC, [Currency] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AccountBalance] OFF;
    END

DROP TABLE [dbo].[AccountBalance];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_AccountBalance]', N'AccountBalance';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_AccountBalance]', N'PK_AccountBalance', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Transaction]...';


GO
CREATE TABLE [dbo].[Transaction] (
    [Id] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating FK_AccountBalance_ToTable...';


GO
ALTER TABLE [dbo].[AccountBalance] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountBalance_ToTable] FOREIGN KEY ([AccountId]) REFERENCES [dbo].[Account] ([AccountId]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[AccountBalance] WITH CHECK CHECK CONSTRAINT [FK_AccountBalance_ToTable];


GO
PRINT N'Update complete.'
GO
