//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalanceMonitor.Database.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAudits = new HashSet<AccountAudit>();
            this.AccountDailyBalances = new HashSet<AccountDailyBalance>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<AccountAudit> AccountAudits { get; set; }
        public virtual ICollection<AccountDailyBalance> AccountDailyBalances { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
