//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalanceMonitor.Database.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public System.Guid AggregateId { get; set; }
        public string Type { get; set; }
        public int Version { get; set; }
        public string Payload { get; set; }
    
        public virtual Aggregate Aggregate { get; set; }
    }
}
